/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bots_CEngineAccess */

#ifndef _Included_bots_CEngineAccess
#define _Included_bots_CEngineAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bots_CEngineAccess
 * Method:    request
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bots_CEngineAccess_request
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
